name: Deploy Hetzner

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hetzner-prod
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}
      - name: Deploy
        env:
          HETZNER_HOST: ${{ secrets.HETZNER_HOST }}
        run: shared/tools/deploy_hetzner.sh


